SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT I.ITEM_ID
    FROM ITEM_INFO I
    RIGHT JOIN ITEM_TREE T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE T.PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC