WITH RECURSIVE ECOLI_GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ED.ID, ED.PARENT_ID, EG.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA ED
    JOIN ECOLI_GENERATION EG
    ON ED.PARENT_ID = EG.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM (
    SELECT ID, GENERATION
    FROM ECOLI_GENERATION
    WHERE ID NOT IN (
        SELECT DISTINCT PARENT_ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NOT NULL
    )
) AS NO_CHILD
GROUP BY GENERATION
ORDER BY GENERATION;