SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (SELECT ID, IFNULL(FISH_TYPE, 10) AS FISH_TYPE, LENGTH
      FROM FISH_INFO) AS FISH
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE